- name: Установить Docker на Ubuntu
  apt:
    name: docker.io
    state: present
  when: ansible_pkg_mgr == "apt"

- name: Установить Docker на Amazon Linux
  yum:
    name: docker
    state: present
  when: ansible_pkg_mgr == "yum"

- name: Убедиться, что Docker запущен
  service:
   name: docker
   state: started
   enabled: yes
  when: ansible_pkg_mgr in ['apt', 'yum']

- name: Логин в Docker Hub
  community.docker.docker_login:
    registry_url: https://index.docker.io/v1/
    username: "{{ docker_hub_username }}"
    password: "{{ docker_hub_password }}"
  when: ansible_pkg_mgr in ['apt', 'yum']

- name: Запустить контейнер из приватного реестра Docker Hub
  community.docker.docker_container:
    name: my-container
    image: "DevOops52/nginx:v2.3"
    state: started
    ports:
      - "80:80"
  when: ansible_pkg_mgr in ['apt', 'yum']