- name: Install apt-transport-https
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: latest
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Add signing key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  when: ansible_os_family == "Debian"

- name: Add repository into sources list
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  when: ansible_os_family == "Debian"

- name: Установить Docker на Ubuntu
  apt:
    name: docker.io
    state: present
  when: ansible_os_family == "Debian"

- name: Установить Docker на Amazon Linux
  yum:
    name: docker
    state: present
  when: ansible_os_family == "RedHat"

- name: Убедиться, что Docker запущен
  service:
   name: docker
   state: started
   enabled: yes
  when: ansible_os_family in ['Debian', 'RedHat']

- name: Логин в Docker Hub
  community.docker.docker_login:
    registry_url: https://index.docker.io/v1/
    username: "devoops52"
    password: "{{ passwd }}"
  when: ansible_os_family in ['Debian', 'RedHat']

- name: Запустить контейнер из приватного реестра Docker Hub
  community.docker.docker_container:
    name: my-container
    image: "devoops52/apache:v1.0"
    state: started
    ports:
      - "8080:8080"
  when: ansible_os_family in ['Debian', 'RedHat']